services:
  postgres:
    image: postgres:16
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
  redis:
    image: redis:7
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ./redis_data:/data
    env_file:
      - .env
    entrypoint: ['redis-server', '--appendonly', 'yes']
