services:
  # postgres:
  #   image: postgres:16
  #   restart: always
  #   volumes:
  #     - ./postgres-data:/var/lib/postgresql/data
  #   ports:
  #     - '${DB_PORT}:5432'
  #   environment:
  #     POSTGRES_USER: ${DB_USERNAME}
  #     POSTGRES_PASSWORD: ${DB_PASSWORD}
  #     POSTGRES_DB: ${DB_DATABASE}
  ## Queue
  redis_bull:
    image: redis:7
    restart: always
    container_name: redis_bull
    ports:
      - '${REDIS_BULL_PORT}:6379'
    volumes:
      - ./redis_data/bull:/data
    env_file:
      - .env
    entrypoint: ['redis-server', '--appendonly', 'yes']
    networks:
      - backend

  ## Red lock
  redis_lock1:
    image: redis:7
    restart: always
    container_name: redis_lock1
    ports:
      - '${REDIS_LOCK1_PORT}:6379'
    volumes:
      - ./redis_data/lock:/data
    env_file:
      - .env
    entrypoint: ['redis-server', '--appendonly', 'yes']
    networks:
      - backend

  redis_lock2:
    image: redis:7
    restart: always
    container_name: redis_lock2
    ports:
      - '${REDIS_LOCK2_PORT}:6379'
    volumes:
      - ./redis_data/lock:/data
    env_file:
      - .env
    entrypoint: ['redis-server', '--appendonly', 'yes']
    networks:
      - backend

  redis_lock3:
    image: redis:7
    restart: always
    container_name: redis_lock3
    ports:
      - '${REDIS_LOCK3_PORT}:6379'
    volumes:
      - ./redis_data/lock:/data
    env_file:
      - .env
    entrypoint: ['redis-server', '--appendonly', 'yes']
    networks:
      - backend

  redis_lock4:
    image: redis:7
    restart: always
    container_name: redis_lock4
    ports:
      - '${REDIS_LOCK4_PORT}:6379'
    volumes:
      - ./redis_data/lock:/data
    env_file:
      - .env
    entrypoint: ['redis-server', '--appendonly', 'yes']
    networks:
      - backend

  redis_lock5:
    image: redis:7
    restart: always
    container_name: redis_lock5
    ports:
      - '${REDIS_LOCK5_PORT}:6379'
    volumes:
      - ./redis_data/lock:/data
    env_file:
      - .env
    entrypoint: ['redis-server', '--appendonly', 'yes']
    networks:
      - backend

  ## NginX
  nginx:
    image: nginx:1.27.1
    container_name: nginx
    environment:
      - TZ=Asia/Seoul
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always
    networks:
      - backend

  ## Backend
  app:
    image: woogionandon/ecommerce_auction_backend:latest
    container_name: ecommerce_auction_backend
    restart: always
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env
    networks:
      - backend
  # networks:
  backend:
    driver: bridge
