name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${secrets.DOCKER_USERNAME}
        DOCKER_PASSWORD: ${secrets.DOCKER_PASSWORD}

      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Build the docker image
      run: docker buil -t ecommerce_auction_backend .
    - name: taging
      run: docker tag ecommerce_auction_backend:latest woogionandon/ecommerce_auction_backend:latest
    - name: Push to Dockerhhub
      run: docker push woogionandon/ecommerce_auction_backend:latest
