name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build the Docker image
      run: docker build -t ecommerce_auction_backend .

    - name: Tag Docker image
      run: docker tag ecommerce_auction_backend:latest woogionandon/ecommerce_auction_backend:latest

    - name: Push Docker image to DockerHub
      run: docker push woogionandon/ecommerce_auction_backend:latest
