name: CD Pipeline

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # 1. SSH로 EC2에 접속하여 기존 컨테이너를 중지(docker-compose down)하고 최신 이미지를 pull 한 후, 다시 실행
      - name: Deploy to EC2 using SSH
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ecommerce_auction_db_server
            sudo su -  
            docker-compose down  
            docker-compose pull 
            docker-compose up -d  

      # 2. 배포 완료 후 로그 확인 (선택 사항)
      - name: Check logs
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker-compose ps
