name: CD Pipeline

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Pull Docker Image
      run: sudo docker pull woogionandon/ecommerce_auction_backend:latest
    - name: Delete Old docker container
      run: sudo docker rm -f ecommerce_auction_backend || true
    - name: Run Docker Container
      run: sudo docker run -d -p 3000:3000 --name ecommerce_auction_backend woogionandon/ecommerce_auction_backend
