name: CD Pipeline

on:
  workflow_run:
    workflows: ['Docker Image CI']
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # 1. SSH로 EC2에 접속하여 기존 컨테이너를 중지(docker-compose down)하고 최신 이미지를 pull 한 후, 다시 실행
      - name: Deploy to EC2 using SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ecommerce_auction_db_server

            echo "DB_HOST=${{ secrets.DB_HOST }}" > .env
            echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
            echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
            echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
            echo "PORT=${{ secrets.PORT }}" >> .env
            echo "HOST=${{ secrets.HOST }}" >> .env
            echo "RUNTIME=${{ secrets.RUNTIME }}" >> .env
            echo "SERVICE_NAME=${{ secrets.SERVICE_NAME }}" >> .env
            echo "URL=${{ secrets.URL }}" >> .env
            echo "HASH_ROUNDS=${{ secrets.HASH_ROUNDS }}" >> .env
            echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
            echo "JWT_ACCESS_EXP=${{ secrets.JWT_ACCESS_EXP }}" >> .env
            echo "JWT_REFRESH_EXP=${{ secrets.JWT_REFRESH_EXP }}" >> .env
            echo "API_SECRET=${{ secrets.API_SECRET }}" >> .env
            echo "CHANNEL_KEY=${{ secrets.CHANNEL_KEY }}" >> .env
            echo "REDIS_HOST=${{ secrets.REDIS_HOST }}" >> .env
            echo "REDIS_LOCK1_PORT=${{ secrets.REDIS_LOCK1_PORT }}" >> .env
            echo "REDIS_LOCK2_PORT=${{ secrets.REDIS_LOCK2_PORT }}" >> .env
            echo "REDIS_LOCK3_PORT=${{ secrets.REDIS_LOCK3_PORT }}" >> .env
            echo "REDIS_LOCK4_PORT=${{ secrets.REDIS_LOCK4_PORT }}" >> .env
            echo "REDIS_LOCK5_PORT=${{ secrets.REDIS_LOCK5_PORT }}" >> .env
            echo "REDIS_BULL_PORT=${{ secrets.REDIS_BULL_PORT }}" >> .env
            echo "JUSO_API_KEY=${{ secrets.JUSO_API_KEY }}" >> .env

            sudo docker-compose down  
            sudo docker-compose pull 
            sudo docker-compose up -d
